"""Scrapers stored in the database

Revision ID: 459c59f80552
Revises: b596a9791d72
Create Date: 2024-02-01 13:48:25.958266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "459c59f80552"
down_revision: Union[str, None] = "662d8c8df97d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scrapers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "execution_frequency",
            mysql.ENUM("ONCE", "DAILY", "MONTHLY"),
            nullable=False,
            server_default="ONCE"
        ),
        sa.Column("available", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.PrimaryKeyConstraint("id"),
    )

    op.alter_column(
        "process_queue",
        "number_to_port",
        new_column_name="phone_number",
        existing_type=sa.String(length=255),
    )
    op.add_column(
        "process_queue", sa.Column("scraper_id", sa.BigInteger(), nullable=True)
    )
    op.alter_column(
        "process_queue",
        "type",
        existing_type=mysql.ENUM(
            "PORT IN NUMBER",
            "SIM EXTRACTION",
            "FICTIVE NUMBER PORT IN",
            "FICTIVE NUMBER SIM EXTRACTION",
            "UPGRADE STATUS AND DRO",
        ),
        nullable=False,
    )
    op.create_foreign_key(
        "fk_process_queue_scraper_id",
        "process_queue",
        "scrapers",
        ["scraper_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "process_queue",
        "phone_number",
        new_column_name="number_to_port",
        existing_type=sa.String(length=255),
    )
    op.drop_constraint(
        "fk_process_queue_scraper_id", "process_queue", type_="foreignkey"
    )

    op.alter_column(
        "process_queue",
        "type",
        existing_type=mysql.ENUM(
            "PORT IN NUMBER",
            "SIM EXTRACTION",
            "FICTIVE NUMBER PORT IN",
            "FICTIVE NUMBER SIM EXTRACTION",
        ),
        nullable=False,
    )
    op.drop_column("process_queue", "scraper_id")
    op.drop_table("scrapers")
    # ### end Alembic commands ###
