"""add fictive number port in table

Revision ID: 662d8c8df97d
Revises: 
Create Date: 2023-12-23 09:10:35.487505

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "662d8c8df97d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fictive_number_port_in",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("number_to_port", sa.String(length=255), nullable=False),
        sa.Column("fictive_number", sa.String(length=255), nullable=True),
        sa.Column(
            "current_provider_account_number", sa.String(length=255), nullable=True
        ),
        sa.Column("client_authorization_name", sa.String(length=255), nullable=True),
        sa.Column(
            "current_billing_provider_value",
            sa.String(length=50),
            nullable=True,
            comment="this value is for the dropdown in the ui",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fictive_number_port_in")
    # ### end Alembic commands ###
