"""models migrations

Revision ID: b6182088df0d
Revises: 
Create Date: 2024-02-13 00:12:51.076072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6182088df0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fictive_number_port_in',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number_to_port', sa.String(length=255), nullable=False),
    sa.Column('fictive_number', sa.String(length=255), nullable=True),
    sa.Column('current_provider_account_number', sa.String(length=255), nullable=True),
    sa.Column('client_authorization_name', sa.String(length=255), nullable=True),
    sa.Column('current_billing_provider_value', sa.String(length=50), nullable=True, comment='this value is for the dropdown in the ui'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrapers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('execution_frequency', mysql.ENUM('ONCE', 'DAILY', 'MONTHLY'), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process_queue',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('aws_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('type', mysql.ENUM('PORT IN NUMBER', 'SIM EXTRACTION', 'FICTIVE NUMBER PORT IN', 'FICTIVE NUMBER SIM EXTRACTION', 'UPGRADE STATUS AND DRO'), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.ENUM('READY', 'FINISHED', 'ERROR'), nullable=False),
    sa.Column('scraper_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['scraper_id'], ['scrapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_queue')
    op.drop_table('scrapers')
    op.drop_table('fictive_number_port_in')
    # ### end Alembic commands ###
